In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("C:\\Users\\royku\\Sem II Modules\\Sem II\\WQD7006\\Week3\\Titanic.csv")
#df1 = pd.read_csv("C:\\Users\\royku\\Sem II Modules\\Sem II\\WQD7006\\Week3\\titanic1.csv")

In [38]:
df.shape

(891, 8)

In [52]:
df.isnull().sum()

Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Fare        0
Embarked    0
Survived    0
dtype: int64

In [7]:
#Dropping Col which are less relevant

df.drop(['PassengerId','Name','Ticket','Cabin'],axis='columns',inplace=True)

In [11]:
df['Age'] = df['Age'].replace(0, np.nan)

In [12]:
from sklearn.impute import KNNImputer

knn = KNNImputer(n_neighbors=3)

In [18]:
# Non Numerical Col

int_col = [col for col in df.columns if df[col].dtypes != 'O']

In [20]:
df1 = knn.fit_transform(df[int_col])

In [30]:
df1 = pd.DataFrame(df1)
df1.head()

0     1    2    3        4    5
0  3.0  22.0  1.0  0.0   7.2500  0.0
1  1.0  38.0  1.0  0.0  71.2833  1.0
2  3.0  26.0  0.0  0.0   7.9250  1.0
3  1.0  35.0  1.0  0.0  53.1000  1.0
4  3.0  35.0  0.0  0.0   8.0500  0.0

In [44]:
df1 = df1.rename(columns={0: 'Pclass', 1: 'Age', 2: 'SibSp', 3: 'Parch',4: 'Fare', 5: 'Survived'})
df1.head(2)

Pclass   Age  SibSp  Parch     Fare  Survived
0     3.0  22.0    1.0    0.0   7.2500       0.0
1     1.0  38.0    1.0    0.0  71.2833       1.0

In [45]:
df['Age'] = df1['Age']

In [51]:
df['Embarked'].fillna('NA', inplace = True)

In [13]:
#import sys
#!{sys.executable} -m pip install fancyimpute

In [14]:
#from fancyimpute import KNN

#df_new = KNN(k=3).fit_transofrm(df_incomplete)

### ''' Facing Error as fancyimpute was not able to be downloaded. 

In [53]:
# Import LabelEncoder
from sklearn import preprocessing

#creating labelEncoder
le = preprocessing.LabelEncoder()

# Converting string labels into numbers.

df.Sex = le.fit_transform(df.Sex)
df.Embarked = le.fit_transform(df.Embarked)

In [54]:
#Checking for NA value

df.columns[df.isna().any()]

Index([], dtype='object')

In [55]:
'''
#Replacing NA values by mean for Age

df.Age = df.Age.fillna(df.Age.mean())
df.head(10)'''

'\n#Replacing NA values by mean for Age\n\ndf.Age = df.Age.fillna(df.Age.mean())\ndf.head(10)'

In [56]:
df.Age =  df.Age.round()

In [57]:
df.head(10)

Pclass  Sex   Age  SibSp  Parch     Fare  Embarked  Survived
0       3    1  22.0      1      0   7.2500         3         0
1       1    0  38.0      1      0  71.2833         0         1
2       3    0  26.0      0      0   7.9250         3         1
3       1    0  35.0      1      0  53.1000         3         1
4       3    1  35.0      0      0   8.0500         3         0
5       3    1  24.0      0      0   8.4583         2         0
6       1    1  54.0      0      0  51.8625         3         0
7       3    1   2.0      3      1  21.0750         3         0
8       3    0  27.0      0      2  11.1333         3         1
9       2    0  14.0      1      0  30.0708         0         1

In [58]:
#Creating Dependent & independent variable

independent = df.drop('Survived',axis='columns')
target = df.Survived

In [68]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(independent,target,test_size=0.25)

In [69]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [70]:
model.fit(X_train,y_train)

GaussianNB()

In [71]:
model.score(X_test,y_test)

0.7937219730941704

In [72]:
y_test[0:10]

786    1
872    0
457    1
135    0
279    1
552    0
621    1
101    0
49     0
843    0
Name: Survived, dtype: int64

In [73]:
model.predict(X_test[0:10])

array([1, 0, 1, 0, 1, 0, 0, 0, 1, 0], dtype=int64)

In [74]:
model.predict_proba(X_test[0:10])

array([[0.31259251, 0.68740749],
       [0.74047306, 0.25952694],
       [0.0495838 , 0.9504162 ],
       [0.56456482, 0.43543518],
       [0.36661355, 0.63338645],
       [0.94375149, 0.05624851],
       [0.673163  , 0.326837  ],
       [0.95870245, 0.04129755],
       [0.32674747, 0.67325253],
       [0.7742498 , 0.2257502 ]])

In [75]:
from sklearn.model_selection import cross_val_score
cross_val_score(GaussianNB(),X_train, y_train, cv=4)

array([0.78443114, 0.74850299, 0.77844311, 0.83832335])

In [90]:
from sklearn.linear_model import LogisticRegression

lg_clf = LogisticRegression(solver='saga', max_iter=10000)

In [91]:
lg_clf.fit(X_train,y_train)

LogisticRegression(max_iter=10000, solver='saga')

In [92]:
y_pred = lg_clf.predict(X_test)

In [93]:
from sklearn.metrics import accuracy_score, confusion_matrix

In [94]:
acc = accuracy_score(y_test,y_pred)
acc

0.7892376681614349

In [87]:
cm =  confusion_matrix(y_test,y_pred)
cm

array([[118,  21],
       [ 26,  58]], dtype=int64)